# Generated by Django 5.1.3 on 2024-11-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리 목록'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='lion_blog_category',
        ),
    ]
